### PR TITLE
Add Package Manifest (package.json) for Ardity

### PR DESCRIPTION
**Pull request by tedliou**
Hi everyone,

I've added a Package Manifest (package.json) to Ardity to allow Unity developers to use Package Manager to manage it. This will make it easier to install and update Ardity, as well as manage its dependencies.

Changes:

1. Added package.json file to UnityProject/Assets/Ardity
2. Updated README.md file to include instructions on how to install Ardity using Package Manager

Testing:

I've tested the changes on my local machine and they seem to be working as expected. I would appreciate it if you could take a look and let me know if you have any feedback.

Thanks,
Ted

### CODE REVIEW

**Comment by dwilches** [comment]
Hello Ted!

Thanks a lot for taking the time to submit this improvement.
I've merged your PR as commit 19098750697d6c601e9df2022ef8910fc3ca5ca6 after making some changes to the README and removing some extra files (I left only the package.json).

Thanks again,
Daniel Wilches.

**Comment by tedliou** [comment]
Hi @dwilches,

Due to the Unity Package Manager's requirements, if a script is divided into Runtime and Editor components, all scripts must be categorized into separate Runtime and Editor directories, and an Assembly Definition must be used for referencing outside the package. This is why I made the changes to the Runtime Script location and created an Assembly Definition in commit 1e81c46. Without these changes, developers would not be able to install and use Ardity through the Package Manager.

Thanks,
Ted

**Comment by dwilches** [comment]
@tedliou Thanks for the clarification, I've updated the master branch with those changes too.
Regards.

**Comment by tedliou** [comment]
Hi @dwilches,

I noticed that the 095041a you pushed does not include the UnityProject/Assets/Ardity/package.json file from the original 1909875. This will cause developers to encounter an error when importing the package because the package.json file is missing.

I recommend merging 1909875 or 40f7653 into the master branch to resolve this issue.

Thanks,
Ted

**Comment by dwilches** [comment]
Mmm, so I ended up removing the original file I merged. I'll fix it later
today. Thanks for checking.

**Comment by dwilches** [comment]
Hello,

I've updated the branch with the missing file. Could you give it a try? I hope this time I got everything right.
Thing is, I no longer have Unity to test myself. I haven't used it for like 7 years but I still keep updating this package as it's been useful for other people.

Regards.

**Comment by tedliou** [comment]
Hi @dwilches,


There are no issues with the current version. Many digital media design students really like Ardity, it's a fantastic tool!

Thanks,
Ted

**Pull request closed without merging**
